-- Insert sample products into cmall_dd table
INSERT INTO cmall_dd (name, price, original_price, image, category, condition, description, size, brand, color, material)
VALUES
    ('Celana Jeans Vintage Levi''s 501', 675000, 1335000, '/images/🇰🇷🇷🇸Korean-Serbian Couple Q&A： Marriage, How We Met & Life Together ｜ 한국 세르비아인 커플_frame_1-30.jpg', 'pants', 'Good', 'Celana jeans vintage Levi''s 501 klasik dalam kondisi sangat baik', '32W x 32L', 'Levi''s', 'blue', 'denim'),
    ('Kaos Band Vintage', 375000, 600000, '/images/🇰🇷🇷🇸Korean-Serbian Couple Q&A： Marriage, How We Met & Life Together ｜ 한국 세르비아인 커플_frame_2-00.jpg', 'shirts', 'Excellent', 'Kaos band vintage asli, lembut dan nyaman', 'L', 'Hanes', 'black', 'cotton'),
    ('Blazer Wol', 825000, 2250000, '/images/🇰🇷🇷🇸Korean-Serbian Couple Q&A： Marriage, How We Met & Life Together ｜ 한국 세르비아인 커플_frame_2-30.jpg', 'jackets', 'Good', 'Blazer wol profesional, cocok untuk keperluan kantor', 'M', 'Brooks Brothers', 'navy', 'wool'),
    ('Dress Musim Panas Motif Bunga', 525000, 1200000, '/images/🇰🇷🇷🇸Korean-Serbian Couple Q&A： Marriage, How We Met & Life Together ｜ 한국 세르비아인 커플_frame_3-00.jpg', 'dresses', 'Excellent', 'Dress cantik dengan motif bunga untuk musim panas, ringan dan mengalir', 'S', 'Zara', 'floral', 'polyester'),
    ('Celana Chino Khaki', 420000, 975000, '/images/🇰🇷🇷🇸Korean-Serbian Couple Q&A： Marriage, How We Met & Life Together ｜ 한국 세르비아인 커플_frame_3-20.jpg', 'pants', 'Good', 'Celana chino khaki yang nyaman, cocok untuk pakaian kasual', '34W x 30L', 'Gap', 'khaki', 'cotton'),
    ('Sweater Oversized', 480000, 1125000, '/images/🇰🇷🇷🇸Korean-Serbian Couple Q&A： Marriage, How We Met & Life Together ｜ 한국 세르비아인 커플_frame_4-00.jpg', 'shirts', 'Excellent', 'Sweater oversized yang hangat, sempurna untuk layering', 'M', 'H&M', 'cream', 'acrylic'),
    ('Jaket Denim', 570000, 1425000, '/images/🇰🇷🇷🇸Korean-Serbian Couple Q&A： Marriage, How We Met & Life Together ｜ 한국 세르비아인 커플_frame_1-30.jpg', 'jackets', 'Good', 'Jaket denim klasik, serbaguna dan timeless', 'M', 'Levi''s', 'blue', 'denim'),
    ('Celana Formal Hitam', 630000, 1275000, '/images/🇰🇷🇷🇸Korean-Serbian Couple Q&A： Marriage, How We Met & Life Together ｜ 한국 세르비아인 커플_frame_2-00.jpg', 'pants', 'Excellent', 'Celana formal hitam profesional, potongan pas', '30W x 32L', 'Banana Republic', 'black', 'wool blend'),
    ('Kaos Grafis Vintage', 330000, NULL, '/images/🇰🇷🇷🇸Korean-Serbian Couple Q&A： Marriage, How We Met & Life Together ｜ 한국 세르비아인 커플_frame_2-30.jpg', 'shirts', 'Fair', 'Kaos grafis vintage keren dengan desain retro', 'XL', 'Fruit of the Loom', 'white', 'cotton'),
    ('Dress Maxi', 720000, 1800000, '/images/🇰🇷🇷🇸Korean-Serbian Couple Q&A： Marriage, How We Met & Life Together ｜ 한국 세르비아인 커플_frame_3-00.jpg', 'dresses', 'Good', 'Dress maxi elegan, sempurna untuk acara khusus', 'M', 'Free People', 'burgundy', 'viscose'),
    ('Celana Korduroy', 525000, 1050000, '/images/🇰🇷🇷🇸Korean-Serbian Couple Q&A： Marriage, How We Met & Life Together ｜ 한국 세르비아인 커플_frame_3-20.jpg', 'pants', 'Good', 'Celana korduroy retro, nyaman dan stylish', '32W x 30L', 'Urban Outfitters', 'brown', 'corduroy'),
    ('Jaket Kulit', 1275000, 3000000, '/images/🇰🇷🇷🇸Korean-Serbian Couple Q&A： Marriage, How We Met & Life Together ｜ 한국 세르비아인 커플_frame_4-00.jpg', 'jackets', 'Excellent', 'Jaket kulit asli, gaya timeless', 'L', 'Wilson''s Leather', 'black', 'leather')
ON CONFLICT DO NOTHING;

